name: helloworld
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.17.0
  pdf: ^3.10.4
  share_plus: ^7.2.1
  open_file: ^3.3.2
  excel: ^2.1.0
  path_provider: ^2.1.1
  printing: ^5.12.0
  font_awesome_flutter: ^10.5.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  get: ^4.6.5
  flutter_launcher_icons: "^0.13.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/pdf.png
    - assets/images/excel.png
    - assets/images/logo_proveedify.png
    - assets/images/LogoProveedify.png
    - assets/jsons/
    - assets/fonts/roboto.ttf
    - assets/images/ISP.png
    - assets/images/Propio.png.

fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700

flutter_launcher_icons:
  android: true
  #ios: true
  image_path: "assets/images/Icon.png"
  min_sdk_android: 21
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
