@baseUrl = http://localhost:3000
@session = mysession=MTc0OTMyNjc1M3xEWDhFQVFMX2dBQUJFQUVRQUFBb180QUFBUVp6ZEhKcGJtY01DQUFHYzNSaGRIVnpCbk4wY21sdVp3d0tBQWhoWTNScGRtRjBaUT09fDEwMNRr-eTvIKdIDTSfFrm61NAAZ06WflPGf2t7gHIC

### Obtener todos los servicios ISP
GET {{baseUrl}}/apis/v1/isp-services
Content-Type: application/json
Cookie: {{session}}

### Obtener servicios ISP por provider_id (ejemplo: provider_id = 1)
GET {{baseUrl}}/apis/v1/isp-services?provider_id=1
Content-Type: application/json
Cookie: {{session}}

### Obtener servicios ISP por provider_id (no existente - espera lista vacía)
GET {{baseUrl}}/apis/v1/isp-services?provider_id=999
Content-Type: application/json
Cookie: {{session}}

### Crear un nuevo servicio ISP
POST {{baseUrl}}/apis/v1/isp-services
Content-Type: application/json
Cookie: {{session}}

{
  "description": "Internet Ultra Rápido 300mb",
  "provider_id": 1,
  "isp_id": 2
}

### Crear servicio duplicado (espera conflicto 409)
POST {{baseUrl}}/apis/v1/isp-services
Content-Type: application/json
Cookie: {{session}}

{
  "description": "Internet Ultra Rápido 300mb",
  "provider_id": 1,
  "isp_id": 2
}

### Crear servicio con campos incompletos (espera 400)
POST {{baseUrl}}/apis/v1/isp-services
Content-Type: application/json
Cookie: {{session}}

{
  "provider_id": 1
}

