@baseUrl = http://localhost:3000

### Obtener todos los ISPs (dropdown CU10.3)
GET {{baseUrl}}/isps
Content-Type: application/json

### Obtener un ISP por ID
GET {{baseUrl}}/isps/2
Content-Type: application/json 

### Crear un nuevo ISP
POST {{baseUrl}}/isps
Content-Type: application/json

{
  "name": "Mi nuevo ISP",
  "ruc": "20999999999"
}
