@baseUrl = http://localhost:3000
@session = mysession=MTc0OTMyNjc1M3xEWDhFQVFMX2dBQUJFQUVRQUFBb180QUFBUVp6ZEhKcGJtY01DQUFHYzNSaGRIVnpCbk4wY21sdVp3d0tBQWhoWTNScGRtRjBaUT09fDEwMNRr-eTvIKdIDTSfFrm61NAAZ06WflPGf2t7gHIC
### Agarrar los providers con una lista de sus ids
POST {{baseUrl}}/providers/fetch-by-ids
Content-Type: application/json
Cookie: {{session}}

{
  "ids": [1,2,3] 
}

###


